weights: /home/longpham/workspaces/one/onedetection/src/onedetection/pretrained/yolov5_v6_1/yolov5x6_v6_1_coco.pt
cfg: ''
data: data/aic22retail.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 200
batch_size: 16
imgsz: 1536
rect: false
resume: null
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/aic22retail
name: yolov5x6_v6_1_aic22retail_1536
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
nosave: false
noval: false
noautoanchor: false
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/aic22retail/yolov5x6_v6_1_aic22retail_1536
